import * as pulumi from "@pulumi/pulumi";
import * as k8s from "@pulumi/kubernetes";
import * as fs from "fs";
import * as path from "path";

/**
 * Node Pool Configuration for Auto-Scaling Aetherium Workers
 *
 * This module provides cloud-agnostic configuration for worker node pools
 * that automatically prepare nodes for Firecracker workloads.
 */

export interface NodePoolConfig {
    name: string;
    minSize: number;
    maxSize: number;
    instanceType: string;
    diskSizeGb: number;
    // Cloud-specific options
    provider: "aws" | "azure" | "gcp" | "local";
    // Aetherium-specific options
    firecrackerVersion?: string;
    kernelUrl?: string;
    rootfsUrl?: string;
}

export interface NodePoolOutput {
    name: string;
    cloudInitScript: string;
    nodeLabels: Record<string, string>;
    nodeTaints: Array<{ key: string; value: string; effect: string }>;
}

/**
 * Generate cloud-init user data for worker nodes
 */
export function generateCloudInitUserData(config: {
    firecrackerVersion?: string;
    kernelUrl?: string;
    rootfsUrl?: string;
}): string {
    const firecrackerVersion = config.firecrackerVersion || "v1.7.0";
    const kernelUrl = config.kernelUrl ||
        "https://s3.amazonaws.com/spec.ccfc.min/img/quickstart_guide/x86_64/kernels/vmlinux.bin";
    const rootfsUrl = config.rootfsUrl || "";

    return `#!/bin/bash
# =============================================================================
# Aetherium Worker Node Bootstrap Script
# Generated by Pulumi
# =============================================================================
set -e

echo "=== Aetherium Worker Node Setup ==="

# Create directories
mkdir -p /var/firecracker
mkdir -p /run/aetherium
mkdir -p /var/log/aetherium

# Load kernel modules
modprobe kvm
modprobe kvm_intel 2>/dev/null || modprobe kvm_amd 2>/dev/null || true
modprobe vhost_vsock

# Make modules persistent
cat > /etc/modules-load.d/aetherium.conf <<EOF
kvm
vhost_vsock
EOF

# Install Firecracker
FIRECRACKER_VERSION="${firecrackerVersion}"
if [ ! -x /usr/local/bin/firecracker ]; then
    echo "Installing Firecracker \${FIRECRACKER_VERSION}..."
    curl -fsSL "https://github.com/firecracker-microvm/firecracker/releases/download/\${FIRECRACKER_VERSION}/firecracker-\${FIRECRACKER_VERSION}-x86_64.tgz" \\
        | tar -xz -C /tmp
    cp "/tmp/release-\${FIRECRACKER_VERSION}-x86_64/firecracker-\${FIRECRACKER_VERSION}-x86_64" /usr/local/bin/firecracker
    chmod +x /usr/local/bin/firecracker
    rm -rf /tmp/release-*
fi

# Download kernel
if [ ! -f /var/firecracker/vmlinux ]; then
    echo "Downloading kernel..."
    curl -fsSL -o /var/firecracker/vmlinux "${kernelUrl}"
fi

${rootfsUrl ? `
# Download rootfs
if [ ! -f /var/firecracker/rootfs.ext4 ]; then
    echo "Downloading rootfs..."
    curl -fsSL -o /var/firecracker/rootfs.ext4 "${rootfsUrl}"
fi
` : "# Rootfs URL not provided - will be handled by node provisioner DaemonSet"}

# Enable IP forwarding
echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-aetherium.conf
sysctl -p /etc/sysctl.d/99-aetherium.conf

echo "=== Setup Complete ==="
`;
}

/**
 * Get node labels for Aetherium worker nodes
 */
export function getWorkerNodeLabels(): Record<string, string> {
    return {
        "aetherium.io/node-type": "worker",
        "aetherium.io/kvm-enabled": "true",
        "aetherium.io/firecracker": "true",
    };
}

/**
 * Get node taints for dedicated worker nodes
 */
export function getWorkerNodeTaints(): Array<{ key: string; value: string; effect: string }> {
    return [
        {
            key: "aetherium.io/worker",
            value: "true",
            effect: "NoSchedule",
        },
    ];
}

/**
 * AWS-specific node pool configuration
 */
export function getAWSNodePoolConfig(config: NodePoolConfig): {
    userData: string;
    labels: Record<string, string>;
    taints: Array<{ key: string; value: string; effect: string }>;
    instanceTypes: string[];
    amiType: string;
} {
    return {
        userData: Buffer.from(generateCloudInitUserData({
            firecrackerVersion: config.firecrackerVersion,
            kernelUrl: config.kernelUrl,
            rootfsUrl: config.rootfsUrl,
        })).toString("base64"),
        labels: getWorkerNodeLabels(),
        taints: getWorkerNodeTaints(),
        // Metal instances for KVM support
        instanceTypes: [
            config.instanceType || "m5.metal",
            "m5d.metal",
            "m5n.metal",
            "c5.metal",
            "c5d.metal",
            "r5.metal",
        ],
        // Amazon Linux 2 with kernel 5.10+
        amiType: "AL2_x86_64",
    };
}

/**
 * Azure-specific node pool configuration
 */
export function getAzureNodePoolConfig(config: NodePoolConfig): {
    customData: string;
    labels: Record<string, string>;
    taints: Array<{ key: string; value: string; effect: string }>;
    vmSize: string;
} {
    return {
        customData: Buffer.from(generateCloudInitUserData({
            firecrackerVersion: config.firecrackerVersion,
            kernelUrl: config.kernelUrl,
            rootfsUrl: config.rootfsUrl,
        })).toString("base64"),
        labels: getWorkerNodeLabels(),
        taints: getWorkerNodeTaints(),
        // Dsv3 series supports nested virtualization
        vmSize: config.instanceType || "Standard_D8s_v3",
    };
}

/**
 * GCP-specific node pool configuration
 */
export function getGCPNodePoolConfig(config: NodePoolConfig): {
    metadata: Record<string, string>;
    labels: Record<string, string>;
    taints: Array<{ key: string; value: string; effect: string }>;
    machineType: string;
} {
    return {
        metadata: {
            "startup-script": generateCloudInitUserData({
                firecrackerVersion: config.firecrackerVersion,
                kernelUrl: config.kernelUrl,
                rootfsUrl: config.rootfsUrl,
            }),
        },
        labels: getWorkerNodeLabels(),
        taints: getWorkerNodeTaints(),
        // N2 series with nested virtualization
        machineType: config.instanceType || "n2-standard-8",
    };
}

/**
 * Create a ConfigMap with cloud-init scripts for manual node setup
 */
export function createCloudInitConfigMap(
    namespace: string,
    config: {
        firecrackerVersion?: string;
        kernelUrl?: string;
        rootfsUrl?: string;
    }
): k8s.core.v1.ConfigMap {
    return new k8s.core.v1.ConfigMap("cloud-init-scripts", {
        metadata: {
            name: "aetherium-cloud-init",
            namespace: namespace,
        },
        data: {
            "bootstrap.sh": generateCloudInitUserData(config),
            "aws-userdata.txt": Buffer.from(generateCloudInitUserData(config)).toString("base64"),
            "azure-customdata.txt": Buffer.from(generateCloudInitUserData(config)).toString("base64"),
        },
    });
}
