name: aetherium-infra
runtime: nodejs
description: Aetherium distributed task execution platform - Infrastructure as Code

config:
  environment:
    description: Deployment environment (development, staging, production)
    default: development
  kubernetes:clusterName:
    description: Kubernetes cluster name
    default: aetherium-cluster
  cloud:provider:
    description: Cloud provider (aws, azure, gcp, local)
    default: local
